apiVersion: v1
kind: Pod
metadata:
  name: shell-demo
spec:
  containers:
    - name: nginx
      image: nginx:1.11.1
      envFrom:
      - configMapRef:
          name: colors
       # valueFrom:
        #  configMapKeyRef:
         #   name: colors
          #  key: favorite